export const CHARACTER_OPTIONS = [
  {
    id: 'barbarian',
    label: 'Barbarian',
    modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Characters/gltf/Barbarian.glb',
    attack: {
      type: 'melee',
      damage: 22,
      cooldown: 0.45,
      range: 2.3,
    },
    weapon: {
      modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Assets/gltf/axe_1handed.gltf',
      handBoneName: 'handslot.r',
      gripPosition: [0, 0, 0],
      gripRotation: [0, 0, Math.PI / 2],
      gripScale: 1.2,
      gripAnchor: [0.85, 0.08, 0.5],
      holdOffset: [0, 0.02, 0],
      tipPosition: [0.95, 0, 0],
    },
  },
  {
    id: 'knight',
    label: 'Knight',
    modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Characters/gltf/Knight.glb',
    attack: {
      type: 'melee',
      damage: 18,
      cooldown: 0.35,
      range: 2.1,
    },
    weapon: {
      modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Assets/gltf/sword_1handed.gltf',
      handBoneName: 'handslot.r',
      gripPosition: [0, 0, 0],
      gripRotation: [0, 0, Math.PI / 2],
      gripScale: 1.25,
      gripAnchor: [0.5, 0.06, 0.5],
      holdOffset: [0, 0.02, 0],
      tipPosition: [1.05, 0, 0],
    },
  },
  {
    id: 'mage',
    label: 'Mage',
    modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Characters/gltf/Mage.glb',
    attack: {
      type: 'projectile',
      damage: 16,
      cooldown: 0.3,
      speed: 12,
    },
    weapon: {
      modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Assets/gltf/staff.gltf',
      handBoneName: 'handslot.r',
      gripPosition: [0.08, 0, 0],
      gripRotation: [0, 0, Math.PI / 2],
      gripScale: 1.2,
      gripAnchor: [0.42, 0.18, 0.5],
      holdOffset: [0, 0.03, 0],
      tipPosition: [1.15, 0, 0],
    },
  },
  {
    id: 'ranger',
    label: 'Ranger',
    modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Characters/gltf/Ranger.glb',
    attack: {
      type: 'projectile',
      damage: 12,
      cooldown: 0.22,
      speed: 15,
    },
    weapon: {
      modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Assets/gltf/bow_withString.gltf',
      handBoneName: 'handslot.r',
      gripPosition: [0.08, 0, 0],
      gripRotation: [0, 0, Math.PI / 2],
      gripScale: 1.15,
      gripAnchor: [0.58, 0.5, 0.5],
      holdOffset: [0, 0.04, 0],
      tipPosition: [0.85, 0.08, 0],
    },
  },
  {
    id: 'rogue',
    label: 'Rogue',
    modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Characters/gltf/Rogue.glb',
    attack: {
      type: 'melee',
      damage: 14,
      cooldown: 0.24,
      range: 1.9,
    },
    weapon: {
      modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Assets/gltf/dagger.gltf',
      handBoneName: 'handslot.r',
      gripPosition: [0, 0, 0],
      gripRotation: [0, 0, Math.PI / 2],
      gripScale: 1.25,
      gripAnchor: [0.46, 0.08, 0.5],
      holdOffset: [0, 0.02, 0],
      tipPosition: [0.8, 0, 0],
    },
  },
  {
    id: 'rogue-hooded',
    label: 'Rogue Hooded',
    modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Characters/gltf/Rogue_Hooded.glb',
    attack: {
      type: 'projectile',
      damage: 13,
      cooldown: 0.25,
      speed: 14,
    },
    weapon: {
      modelUrl: '/models/KayKit_Adventurers_2.0_FREE/Assets/gltf/wand.gltf',
      handBoneName: 'handslot.r',
      gripPosition: [0.02, 0, 0],
      gripRotation: [0, 0, Math.PI / 2],
      gripScale: 1.25,
      gripAnchor: [0.5, 0.1, 0.5],
      holdOffset: [0, 0.02, 0],
      tipPosition: [0.75, 0, 0],
    },
  },
];

export function getCharacterById(characterId) {
  return CHARACTER_OPTIONS.find((option) => option.id === characterId) ?? CHARACTER_OPTIONS[0];
}
